### ISSUE TITLE
Crash during mass contacts deletion

### ISSUE THREAD

**Issue by Perflyst** [SimpleMobileTools/Simple-Contacts#1032]
Deleting a huge amount of contacts crashes the app. It is still possible to get rid of all contacts by starting the deletion multiple times.

Version 6.22.4 from F-Droid

```
type: crash
package: com.simplemobiletools.contacts.pro:104
process: com.simplemobiletools.contacts.pro
processUptime: 11702 + 312 ms
installer: com.android.packageinstaller

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 11(offset:11).state:1140 com.simplemobiletools.commons.views.MyRecyclerView{7c31ee2 VFED..... ........ 0,0-1080,1786 #7f09020d app:id/fragment_list}, adapter:g4.d@6493273, layout:com.simplemobiletools.commons.views.MyLinearLayoutManager@27bb530, context:com.simplemobiletools.contacts.pro.activities.MainActivity@e23dff
	at androidx.recyclerview.widget.RecyclerView$w.I(SourceFile:297)
	at androidx.recyclerview.widget.e.i(SourceFile:15)
	at androidx.recyclerview.widget.e.c(SourceFile:16)
	at androidx.recyclerview.widget.e.d(SourceFile:23)
	at androidx.recyclerview.widget.e.g(SourceFile:4)
	at androidx.recyclerview.widget.e.run(SourceFile:71)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Contacts/issues/514.

**Comment by tibbi** [comment]
try updating to 6.22.7, you use a old version
