### ISSUE TITLE
IllegalArgumentException: both or neither of ACCOUNT_NAME AND ACCOUNT_TYPE when saving contact

### ISSUE THREAD

**Issue by emilhem** [SimpleMobileTools/Simple-Contacts#297]
I'm using v5.1.0 on a One Plus X running LineageOS 14.1-20181027-NIGHTLY-onyx (Android 7.1.2)

When I'm trying to add a new user with only phone number and name there's an exception, see screenshot below:
![screenshot_20181102](https://user-images.githubusercontent.com/1503789/47928573-0182af00-dec7-11e8-8b42-2d0021c210fb.png)

From LogCat:
```
Writing exception to parcel
java.lang.IllegalArgumentException: Must specify both or neither of ACCOUNT_NAME and ACCOUNT_TYPE; URI: content://com.android.contacts/raw_contacts, calling user: com.simplemobiletools.contacts, calling package:com.simplemobiletools.contacts
 at com.android.providers.contacts.ContactsProvider2.resolveAccount(ContactsProvider2.java:2982)
 at com.android.providers.contacts.ContactsProvider2.resolveAccountWithDataSet(ContactsProvider2.java:3027)
 at com.android.providers.contacts.ContactsProvider2.replaceAccountInfoByAccountId(ContactsProvider2.java:10369)
 at com.android.providers.contacts.ContactsProvider2.insertRawContact(ContactsProvider2.java:3068)
 at com.android.providers.contacts.ContactsProvider2.insertInTransaction(ContactsProvider2.java:2876)
 at com.android.providers.contacts.AbstractContactsProvider.insert(AbstractContactsProvider.java:181)
 at com.android.providers.contacts.ContactsProvider2.insert(ContactsProvider2.java:2435)
 at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:302)
 at com.android.providers.contacts.AbstractContactsProvider.applyBatch(AbstractContactsProvider.java:286)
 at com.android.providers.contacts.ContactsProvider2.applyBatch(ContactsProvider2.java:2570)
 at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:316)
 at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:192)
 at android.os.Binder.execTransact(Binder.java:565)
```

**Comment by tibbi** [comment]
what contact source are you saving to? I mean the last field at the Edit contact screen. Try if some other one works.

**Comment by emilhem** [comment]
It said some random number..., when I changed it to PHONE it worked as expected! Thanks for the help!

**Comment by tibbi** [comment]
that number was probably Telegram, you cannot save in that anymore
