### ISSUE TITLE
Attempt to save new contact with photo crashes the app

### ISSUE THREAD

**Issue by preobrazhensky0** [SimpleMobileTools/Simple-Contacts#631]
Hello,

I found the following bug in old Google Play app version and app version from the `master` branch (at this moment). I was able to achieve this on Android Studio emulator (30.2.6-6962233) with Android 9.0 (API 28) and device with Android 8.1.

**Steps:**
1.	Start the app
2.	Deny contacts permission
3.	Press new contact button
4.	Press add photo button
5.	Press “Choose photo”
6.	Select existing file
7.	Press “Done”
8.	Press save - app crashes and contact is not added

**Stack trace:**
`java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1039)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1006)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:956)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:747)
        at com.simplemobiletools.contacts.pro.helpers.LocalContactsHelper.getPhotoByteArray(LocalContactsHelper.kt:80)
        at com.simplemobiletools.contacts.pro.helpers.LocalContactsHelper.convertContactToLocalContact(LocalContactsHelper.kt:129)
        at com.simplemobiletools.contacts.pro.helpers.LocalContactsHelper.insertOrUpdateContact(LocalContactsHelper.kt:33)
        at com.simplemobiletools.contacts.pro.helpers.ContactsHelper.insertContact(ContactsHelper.kt:1171)
        at com.simplemobiletools.contacts.pro.activities.EditContactActivity.insertNewContact(EditContactActivity.kt:1000)
        at com.simplemobiletools.contacts.pro.activities.EditContactActivity.access$insertNewContact(EditContactActivity.kt:45)
        at com.simplemobiletools.contacts.pro.activities.EditContactActivity$saveContact$$inlined$apply$lambda$1.invoke(EditContactActivity.kt:890)
        at com.simplemobiletools.contacts.pro.activities.EditContactActivity$saveContact$$inlined$apply$lambda$1.invoke(EditContactActivity.kt:45)
        at com.simplemobiletools.commons.helpers.ConstantsKt$ensureBackgroundThread$1.run(Constants.kt:333)
        at java.lang.Thread.run(Thread.java:764)`

Thank you and good luck!

**Comment by tibbi** [comment]
what app version is that? The latest from Github?

**Comment by preobrazhensky0** [comment]
yes, latest `master` - https://github.com/SimpleMobileTools/Simple-Contacts. Also can be reproduced in the app from Google Play store https://play.google.com/store/apps/details?id=com.simplemobiletools.contacts

**Comment by tibbi** [comment]
should be working already
