### ISSUE TITLE
Illegal character in scheme name while export contacts

### ISSUE THREAD

**Issue by Slake07** [SimpleMobileTools/Simple-Contacts#714]
Hi there,

While exporting contacts, I am getting below error in logcat:

`Non-fatal Exception: java.lang.Exception: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 6: Google talk:8503801621
at com.allbackup.helpers.VcfExporter.exportContacts(VcfExporter.java:137)
       at com.allbackup.workers.WorkerViewModel$backupContactData$2.invokeSuspend(WorkerViewModel.java:151)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)`

I am using export logic in my application. Below is part of code in which I am getting error:

`contact.IMs.forEach {mIM->
                        try {
                            val mLabel = if(mIM.label.isNullOrEmpty()) mIM.value else mIM.label
                            val impp = when (mIM.type) {
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_AIM -> Impp.aim(mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_YAHOO -> Impp.yahoo(mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_MSN -> Impp.msn(mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_ICQ -> Impp.icq(mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_SKYPE -> Impp.skype(mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_GOOGLE_TALK -> Impp(HANGOUTS, mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_QQ -> Impp(QQ, mIM.value)
                                ContactsContract.CommonDataKinds.Im.PROTOCOL_JABBER -> Impp(JABBER, mIM.value)
                                else -> Impp(mLabel, mIM.value)
                            }
                            card.addImpp(impp)
                        }catch (e: Exception){
                            crashlytics.setCustomKey("Contact IMs", "Label: "+mIM.label+" Value: "+mIM.value+" Type: "+mIM.type)
                            Applog.e(TAG, e)
                        }
                    }`

**Comment by tibbi** [comment]
which contact is it? What values does it have filled at the Im fields? If I can reproduce the issue, Ill be able to fix it quickly too.

**Comment by Slake07** [comment]
@tibbi Actually, this issue is coming into customers device. So I can't reproduce to trace it. There are lots of report of this issue in last 1 year. Now, I want to solve this.
